version: 0.2

phases:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
     - './aws-device-farm-sample-app-for-android/app/build/outputs/**/*.apk'
  discard-paths: yes
